# Generated by Django 3.1.5 on 2021-02-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='gender',
            field=models.CharField(choices=[('O', 'Other'), ('M', 'male'), ('F', 'female')], default='F', max_length=1),
        ),
    ]
