# Generated by Django 3.1.5 on 2021-02-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0002_auto_20210207_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('O', 'Other'), ('F', 'female')], default='F', max_length=1),
        ),
    ]
